services:
  smallc-ide:
    image: smallc-ide:amd64
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: '1'
    restart: unless-stopped
