/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/pack_utils.ts
 *
 * Contains bundled source code of utils (MsgT, ToutDef, etc.) for client-side generation.
 */

export const BUNDLED_UTILS_CODE = `
const { sha256: nobleSha256 } = require('@noble/hashes/sha2');
const bigInt = require('big-integer');

// --- src/utils/base58.ts ---


class Base58 {
    constructor() {
        this.alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
        this.validRegex = /^[1-9A-HJ-NP-Za-km-z]+\$/;
        this.base = (0, bigInt.default)(58);
    }
    encode(input) {
        const inputArray = Array.isArray(input) ? input : Array.from(input);
        const bi = bigInt.default.fromArray(inputArray, 256, false);
        const chars = [];
        let currentBi = bi;
        while (currentBi.compare(this.base) >= 0) {
            const mod = currentBi.mod(this.base);
            chars.unshift(this.alphabet[mod.toJSNumber()]);
            currentBi = currentBi.subtract(mod).divide(this.base);
        }
        chars.unshift(this.alphabet[currentBi.toJSNumber()]);
        for (let i = 0; i < inputArray.length; i++) {
            if (inputArray[i] === 0x00) {
                chars.unshift(this.alphabet[0]);
            }
            else {
                break;
            }
        }
        return chars.join('');
    }
    decode(input) {
        let bi = (0, bigInt.default)(0);
        let leadingZerosNum = 0;
        for (let i = input.length - 1; i >= 0; i--) {
            const alphaIndex = this.alphabet.indexOf(input[i]);
            if (alphaIndex < 0) {
                throw new Error("Invalid character");
            }
            bi = bi.add((0, bigInt.default)(alphaIndex).multiply(this.base.pow(input.length - 1 - i)));
            if (input[i] === "1") {
                leadingZerosNum++;
            }
            else {
                leadingZerosNum = 0;
            }
        }
        const bytes = bi.toArray(256).value;
        while (leadingZerosNum-- > 0) {
            bytes.unshift(0);
        }
        return bytes;
    }
}





// --- src/utils/index.ts ---



const sha2_js_1 = require("@noble/hashes/sha2.js");
const base58_1 = __importDefault(require("./base58"));


function nib(charCode) {
    if (charCode >= 48 && charCode <= 57)
        return charCode - 48;
    if (charCode >= 97 && charCode <= 102)
        return charCode - 97 + 10;
    if (charCode >= 65 && charCode <= 70)
        return charCode - 65 + 10;
    return 0;
}
function hexToBytes(hex) {
    const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
    const len = clean.length;
    const out = new Uint8Array(Math.floor(len / 2));
    for (let i = 0, j = 0; i < len; i += 2, j++) {
        out[j] = (nib(clean.charCodeAt(i)) << 4) | nib(clean.charCodeAt(i + 1));
    }
    return out;
}
function addressHexToString(bytes, version) {
    const hash = bytes.slice(0);
    const versionedHash = new Uint8Array([version, ...hash]);
    const checksum = (0, sha2_js_1.sha256)((0, sha2_js_1.sha256)(versionedHash));
    const result = new Uint8Array([...versionedHash, ...checksum.slice(0, 4)]);
    return base58_1.default.encode(result);
}
function bytesToHex(bytes) {
    const lut = Array.from({ length: 256 }, (_, i) => i.toString(16).padStart(2, "0"));
    let s = "";
    for (let i = 0; i < bytes.length; i++)
        s += lut[bytes[i]];
    return s;
}
function bytesToString(bytes) {
    let str = "";
    for (let i = 0; i < bytes.length; i++)
        str += String.fromCharCode(bytes[i]);
    return str;
}
function hashReverse(h) {
    let s = "";
    for (let i = 0; i < 64; i += 2) {
        s = h.charAt(i) + h.charAt(i + 1) + s;
    }
    return s;
}
function rawTxDecode(hex) {
    hex = hex.toLowerCase();
    const r = new Reader();
    r.StrToByte(hex);
    return r;
}
function decode(r) {
    const version = r.readInt32();
    if ((version & 0x20) == 0) {
        const dcount = r.readVarInt();
        const txDef = [];
        let lockTime = 0;
        for (let i = 0; i < dcount; i++) {
            let t = r.read(1);
            t = t[0];
            let c;
            switch (t) {
                case new Uint8Array([0]):
                    c = new VertexDef();
                    break;
                case new Uint8Array([1]):
                    c = new BorderDef();
                    break;
                case new Uint8Array([2]):
                    c = new PolygonDef();
                    break;
                case new Uint8Array([4]):
                    c = new RightDef();
                    break;
                case new Uint8Array([5]):
                    c = new RightSetDef();
                    break;
                case new Uint8Array([0xfc]):
                    c = new SeparatorDef();
                    break;
            }
            c?.read(r);
            txDef.push(c);
        }
        let count = r.readVarInt();
        const tIn = [];
        for (let i = 0; i < count; i++) {
            const t = new TinDef();
            t.read(r);
            tIn.push(t);
        }
        count = r.readVarInt();
        const tOut = [];
        for (let i = 0; i < count; i++) {
            const t = new ToutDef();
            t.read(r);
            tOut.push(t);
        }
        if ((version & 0x10) == 0) {
            lockTime = r.readInt32();
            console.log("lockTime", lockTime);
        }
        count = r.readVarInt();
        const signatureScripts = [];
        for (let i = 0; i < count; i++) {
            signatureScripts.push(r.readScript());
        }
    }
}
function bytesToHex2(bytes) {
    const hex = [];
    for (let i = 0; i < bytes.length; i++) {
        hex.push((bytes[i] >>> 4).toString(16));
        hex.push((bytes[i] & 0xf).toString(16));
    }
    return hex.join("");
}
function bin2hex(str) {
    let hex = "", num;
    str = padLeft(str, 4);
    for (let i = str.length; i >= 4; i -= 4) {
        num = parseInt(str.slice(i - 4, i), 2);
        if (isNaN(num)) {
            throw new Error("Invalid binary character.");
        }
        hex = num.toString(16) + hex;
    }
    return hex;
}
function padLeft(str, bits) {
    bits = bits || 8;
    const missing = str.length % bits;
    return (missing ? new Array(bits - missing + 1).join("0") : "") + str;
}


// --- src/utils/packer.ts ---


class Packer {
    constructor() {
        this.dest = [];
    }
    Bytes() {
        return new Uint8Array(this.dest);
    }
    PackC(c) {
        this.dest.push(c);
    }
    PackV(v) {
        this.dest.push(v & 0xFF);
        this.dest.push((v >> 8) & 0xFF);
        this.dest.push((v >> 16) & 0xFF);
        this.dest.push((v >> 24) & 0xFF);
    }
    PackP(v) {
        if (typeof v !== 'bigint') {
            v = BigInt(Math.round(Number(v)));
        }
        this.dest.push(Number(v) & 0xFF);
        this.dest.push(Number(v >> BigInt(8)) & 0xFF);
        this.dest.push(Number(v >> BigInt(16)) & 0xFF);
        this.dest.push(Number(v >> BigInt(24)) & 0xFF);
        this.dest.push(Number(v >> BigInt(32)) & 0xFF);
        this.dest.push(Number(v >> BigInt(40)) & 0xFF);
        this.dest.push(Number(v >> BigInt(48)) & 0xFF);
        this.dest.push(Number(v >> BigInt(56)) & 0xFF);
    }
    PackH(v) {
        this.dest.push((nib(v.charCodeAt(0)) << 4 | nib(v.charCodeAt(1))) & 0xFF);
    }
    PackCs(c) {
        for (let i = 0; i < c.length; i++) {
            this.PackC(c[i]);
        }
    }
    PackVs(v) {
        for (let i = 0; i < v.length; i++) {
            this.PackV(v[i]);
        }
    }
    PackHs(v) {
        for (let i = 0; i < v.length; i += 2) {
            this.dest.push((nib(v.charCodeAt(i)) << 4 | nib(v.charCodeAt(i + 1))) & 0xFF);
        }
    }
    WriteVarInt(val) {
        if (typeof val === "bigint" && val <= BigInt(0xFFFFFFFF)) {
            val = Number(val);
        }
        if (typeof val === "number") {
            if (val < 0xfd) {
                this.dest.push(val);
                return;
            }
            if (val <= 0xFFFF) {
                this.dest.push(0xFD);
                this.dest.push(val & 0xFF);
                this.dest.push((val >> 8) & 0xFF);
                return;
            }
            if (val <= 0xFFFFFFFF) {
                this.dest.push(0xFE);
                this.PackV(val);
                return;
            }
        }
        this.dest.push(0xFF);
        this.PackP(val);
    }
    Merge(val) {
        this.dest = this.dest.concat(Array.from(val));
    }
}



// --- src/utils/reader.ts ---




class Reader {
    constructor() {
        this.src = new Uint8Array(0);
        this.pos = 0;
        this.len = 0;
    }
    EOF() { return this.pos >= this.len; }
    SetBytes(s) {
        this.src = s;
        this.pos = 0;
        this.len = s.length;
    }
    StrToByte(s) {
        this.src = hexToBytes(s);
        this.pos = 0;
        this.len = this.src.length;
    }
    readBH() {
        const v = this.readInt32();
        const Prev = this.readHash();
        const Merkle = this.readHash();
        const Timestamp = this.readInt32();
        const ContractExec = this.readInt64();
        const Nonce = this.readInt32();
        return { Version: v, PrevBlock: Prev, MerkleRoot: Merkle, Timestamp, ContractExec, Nonce };
    }
    read(n) {
        const remaining = Math.max(0, Math.min(n, this.len - this.pos));
        const out = this.src.subarray(this.pos, this.pos + remaining);
        this.pos += remaining;
        return out;
    }
    readInt32() {
        let sum = 0;
        for (let i = 0; i < 4; i++) {
            if (this.pos >= this.len)
                return sum;
            sum += this.src[this.pos++] << (i * 8);
        }
        if (sum & 0x80000000) {
            sum = (~sum) + 1;
            sum = -sum;
        }
        return sum;
    }
    readInt64() {
        let sum = BigInt(0);
        for (let i = 0; i < 8; i++) {
            if (this.pos >= this.len)
                return sum;
            const d = BigInt(this.src[this.pos++]) << BigInt(i * 8);
            sum += d;
        }
        return sum;
    }
    readScript() {
        const count = this.readVarInt();
        if (!count)
            return '';
        return bytesToHex(this.read(Number(count)));
    }
    readText() {
        const count = Number(this.readVarInt());
        const t = this.read(count);
        let s = '';
        for (let i = 0; i < count; i++)
            s += String.fromCharCode(t[i]);
        return s;
    }
    readOutPoint() {
        const h = this.readHash();
        const i = this.readInt32();
        return { hash: h, index: i };
    }
    readHash() {
        const t = this.read(32);
        return bytesToHex(t);
    }
    readVarInt() {
        const discriminant = this.src[this.pos];
        if (discriminant < 0xfd) {
            this.pos++;
            return discriminant;
        }
        this.pos++;
        let sum = 0;
        const bs = 1 << (discriminant - 0xfc);
        for (let i = 0; i < Math.min(bs, 4); i++) {
            if (this.pos >= this.len)
                return sum;
            sum = sum | ((this.src[this.pos] << (i * 8)) & 0xFFFFFFFF);
            this.pos++;
        }
        if (bs > 4) {
            let big = BigInt(sum);
            for (let i = 4; i < bs; i++) {
                if (this.pos >= this.len)
                    return big;
                big = big | (BigInt(this.src[this.pos]) << BigInt(i * 8));
                this.pos++;
            }
            return big;
        }
        return sum;
    }
    readIntDiscriminant() {
        return this.src[this.pos];
    }
}



// --- src/utils/defs.ts ---


class BorderDef {
    constructor() {
        this.type = 'border';
        this.father = '';
        this.begin = new VertexDef();
        this.end = new VertexDef();
    }
    write0(b, w) {
        if (b.father.length > 0) {
            for (let i = 0; i < 32; i++)
                w.PackC(0);
        }
        else
            w.PackHs(hashReverse(b.father));
        w.Merge(b.begin.write());
        w.Merge(b.end.write());
    }
    read(r) {
        this.father = r.readHash();
        this.begin.read(r);
        this.end.read(r);
    }
    write() {
        const w = new Packer();
        w.PackC(1);
        this.write0(this, w);
        return w.Bytes();
    }
    hashval() {
        const w = new Packer();
        this.write0(this, w);
        const h = (0, sha2_js_1.sha256)(w.Bytes());
        h[0] &= 0xfe;
        return hashReverse(bytesToHex(h));
    }
    data() {
        return {
            father: this.father,
            begin: this.begin.data(),
            end: this.end.data(),
        };
    }
}

class PolygonDef {
    constructor() {
        this.type = 'polygon';
        this.Loops = [];
    }
    read(r) {
        for (let nloops = r.readVarInt(); nloops > 0; nloops--) {
            const loop = [];
            for (let borders = r.readVarInt(); borders > 0; borders--) {
                loop.push(r.readHash());
            }
            this.Loops.push(loop);
        }
    }
    write() {
        const w = new Packer();
        w.PackC(2);
        w.WriteVarInt(this.Loops.length);
        for (let i = 0; i < this.Loops.length; i++) {
            const loop = this.Loops[i];
            w.WriteVarInt(loop.length);
            for (let j = 0; j < loop.length; j++)
                w.PackHs(hashReverse(loop[j]));
        }
        return w.Bytes();
    }
    hashval() {
        const w = new Packer();
        for (let i = 0; i < this.Loops.length; i++) {
            const loop = this.Loops[i];
            for (let j = 0; j < loop.length; j++)
                w.PackHs(hashReverse(loop[j]));
        }
        const h = (0, sha2_js_1.sha256)(w.Bytes());
        return hashReverse(h);
    }
    data() {
        return {
            Loops: this.Loops,
        };
    }
}

class VertexDef {
    constructor() {
        this.type = 'vertex';
        this.lat = 0;
        this.lng = 0;
        this.alt = 0;
    }
    read(r) {
        this.lat = r.readInt32();
        this.lng = r.readInt32();
        this.alt = r.readInt32();
    }
    write() {
        const w = new Packer();
        w.PackV(this.lat);
        w.PackV(this.lng);
        w.PackV(this.alt);
        return w.Bytes();
    }
    hashval() {
        return hashReverse(this.write());
    }
    data() {
        return {
            lat: this.lat,
            lng: this.lng,
            alt: this.alt,
        };
    }
}

class RightDef {
    constructor() {
        this.type = 'right';
        this.father = '';
        this.desc = '';
        this.attrib = 0;
    }
    read(r) {
        this.father = r.readHash();
        const n = r.readVarInt();
        const s = r.read(Number(n));
        this.desc = bytesToString(s);
        this.attrib = r.read(1)[0];
    }
    write() {
        const w = new Packer();
        w.PackC(4);
        w.PackHs(hashReverse(this.father));
        w.WriteVarInt(this.desc.length);
        if (typeof this.desc == 'string') {
            const sp = this.desc.split('');
            for (let i = 0; i < sp.length; i++) {
                sp[i] = String.fromCharCode(sp[i].charCodeAt(0));
            }
            w.Merge(sp);
        }
        else
            w.Merge(this.desc);
        w.PackC(this.attrib);
        return w.Bytes();
    }
    hashval() {
        const w = new Packer();
        w.PackHs(hashReverse(this.father));
        if (typeof this.desc == 'string') {
            const sp = this.desc.split('');
            for (let i = 0; i < sp.length; i++) {
                sp[i] = String.fromCharCode(sp[i].charCodeAt(0));
            }
            w.Merge(sp);
        }
        else
            w.Merge(this.desc);
        w.PackC(this.attrib);
        const h = (0, sha2_js_1.sha256)(w.Bytes());
        return hashReverse(h);
    }
    data() {
        return {
            father: this.father,
            desc: this.desc,
            attrib: this.attrib,
        };
    }
}

class RightSetDef {
    constructor() {
        this.type = 'rightset';
        this.rights = [];
    }
    data() {
        return { rights: this.rights };
    }
    read(r) {
        const n = r.readVarInt();
        for (let i = 0; i < n; i++) {
            this.rights.push(r.readHash());
        }
    }
    write() {
        this.rights.sort((a, b) => {
            for (let k = 0; k < 32; k++) {
                if (a[k] < b[k])
                    return -1;
                if (a[k] > b[k])
                    return 1;
            }
            return 0;
        });
        const w = new Packer();
        w.WriteVarInt(this.rights.length);
        for (let i = 0; i < this.rights.length; i++) {
            w.PackHs(hashReverse(this.rights[i]));
        }
        return w.Bytes();
    }
    hashval() {
        this.rights.sort((a, b) => {
            for (let k = 0; k < 32; k++) {
                if (a[k] < b[k])
                    return -1;
                if (a[k] > b[k])
                    return 1;
            }
            return 0;
        });
        const w = new Packer();
        for (let i = 0; i < this.rights.length; i++) {
            w.PackHs(hashReverse(this.rights[i]));
        }
        const h = (0, sha2_js_1.sha256)(w.Bytes());
        return hashReverse(h);
    }
}

class SeparatorDef {
    constructor() {
        this.type = 'separator';
    }
    read() { }
    write() {
        return [0xfc];
    }
    data() {
        return {};
    }
}

class TinDef {
    constructor() {
        this.type = 'tin';
        this.previousOutPoint = {
            hash: '',
            index: -1,
        };
        this.signatureIndex = -1;
        this.sequence = -1;
    }
    data() {
        return {
            previousOutPoint: this.previousOutPoint,
            signatureIndex: this.signatureIndex,
            sequence: this.sequence,
        };
    }
    read(r) {
        this.previousOutPoint = r.readOutPoint();
        this.previousOutPoint.hash = hashReverse(this.previousOutPoint.hash);
        this.signatureIndex = r.readInt32();
        this.sequence = r.readInt32();
    }
    write() {
        const w = new Packer();
        w.PackHs(hashReverse(this.previousOutPoint.hash));
        w.PackV(this.previousOutPoint.index);
        w.PackV(this.signatureIndex);
        w.PackV(this.sequence);
        return w.Bytes();
    }
    isSeparator() {
        return (this.previousOutPoint.hash ==
            '0000000000000000000000000000000000000000000000000000000000000000' &&
            this.previousOutPoint.index == 0 &&
            this.signatureIndex == 0 &&
            this.sequence == 0);
    }
}

class ToutDef {
    constructor() {
        this.type = 'txout';
        this.tokenType = 0n;
        this.value = 0n;
        this.rights = [];
        this.pkScript = '';
    }
    data() {
        return {
            tokenType: this.tokenType,
            value: this.value,
            rights: this.rights,
            pkScript: this.pkScript,
        };
    }
    read(r) {
        const discriminant = r.readIntDiscriminant();
        this.tokenType = BigInt(r.readVarInt());
        if (discriminant >= 0xfd) {
            const bs = 1 << (discriminant - 0xfc);
            if (bs <= 4) {
                this.tokenType = this.tokenType & BigInt(0xFFFFFFFF);
            }
        }
        if (this.tokenType == BigInt(0xfc)) {
            r.readScript();
            return;
        }
        if ((this.tokenType & 1n) == 1n) {
            this.value = BigInt(hashReverse(r.readHash()));
        }
        else {
            this.value = BigInt(r.readInt64());
        }
        if ((this.tokenType & 2n) != 0n) {
            this.rights = [hashReverse(r.readHash())];
        }
        this.pkScript = r.readScript();
    }
    write() {
        const w = new Packer();
        w.WriteVarInt(this.tokenType);
        if (this.tokenType == BigInt(0xfc)) {
            w.WriteVarInt(0);
            return w.Bytes();
        }
        if ((this.tokenType & 1n) == 0n)
            w.PackP(this.value);
        else
            w.PackHs(hashReverse(this.value));
        if ((this.tokenType & 2n) != 0n)
            w.PackHs(hashReverse(this.rights[0]));
        w.WriteVarInt(this.pkScript.length / 2);
        w.PackHs(this.pkScript);
        return w.Bytes();
    }
    isSeparator() {
        return this.tokenType == BigInt(0xfc);
    }
}



// --- src/utils/msgTools.ts ---



const sha2_js_1 = require("@noble/hashes/sha2.js");




class MsgT {
    constructor() {
        this.signatureScripts = [];
        this.version = 0x11;
        this.txDef = [];
        this.tIn = [];
        this.tOut = [];
        this.signatureScripts = [];
        this.lockTime = 0;
    }
    data() {
        const t = {
            version: this.version,
            TxDef: [],
            TIn: [],
            TOut: [],
            SignatureScripts: this.signatureScripts,
        };
        for (let i = 0; i < this.txDef.length; i++) {
            t.TxDef.push(this.txDef[i].data());
        }
        for (let i = 0; i < this.tIn.length; i++) {
            t.TIn.push(this.tIn[i].data());
        }
        for (let i = 0; i < this.tOut.length; i++) {
            t.TOut.push(this.tOut[i].data());
        }
        return t;
    }
    fromData(d) {
        this.signatureScripts = d.SignatureScripts;
        for (let i = 0; i < d.TIn.length; i++) {
            const t = new TinDef();
            t.previousOutPoint = d.TIn[i].previousOutPoint;
            t.signatureIndex = d.TIn[i].signatureIndex;
            t.sequence = d.TIn[i].sequence;
            this.tIn.push(t);
        }
        for (let i = 0; i < d.TOut.length; i++) {
            const t = new ToutDef();
            t.tokenType = d.TOut[i].tokenType;
            t.value = d.TOut[i].value;
            t.rights = d.TOut[i].rights;
            t.pkScript = d.TOut[i].pkScript;
            this.tOut.push(t);
        }
    }
    assignSigIndex() {
        let signatureIndex = 0;
        const addresses = [];
        for (let i = 0; i < this.tIn.length; i++) {
            const sid = addresses.findIndex((n) => n === this.tIn[i].signatureIndex);
            if (sid >= 0) {
                this.tIn[i].signatureIndex = sid;
            }
            else {
                addresses.push(this.tIn[i].signatureIndex);
                this.tIn[i].signatureIndex = signatureIndex;
                signatureIndex++;
            }
        }
        return addresses;
    }
    encode(mode) {
        const w = new Packer();
        w.PackV(this.version);
        let count = 0;
        if ((this.version & 0x20) === 0) {
            count = this.txDef.length;
            if ((mode & 2) === 0) {
                for (let i = 0; i < this.txDef.length; i++) {
                    if (this.txDef[i].type === 'separator') {
                        count = i;
                        break;
                    }
                }
            }
            w.WriteVarInt(count);
            for (let i = 0; i < count; i++) {
                w.Merge(this.txDef[i].write());
            }
        }
        count = this.tIn.length;
        if ((mode & 2) === 0) {
            for (let i = 0; i < this.tIn.length; i++) {
                if (this.tIn[i].isSeparator()) {
                    count = i;
                    break;
                }
            }
        }
        w.WriteVarInt(count);
        for (let i = 0; i < count; i++) {
            w.Merge(this.tIn[i].write());
        }
        count = this.tOut.length;
        if ((mode & 2) === 0) {
            for (let i = 0; i < this.tOut.length; i++) {
                if (this.tOut[i].isSeparator()) {
                    count = i;
                    break;
                }
            }
        }
        w.WriteVarInt(count);
        for (let i = 0; i < count; i++) {
            w.Merge(this.tOut[i].write());
        }
        if ((this.version & 0x10) === 0) {
            w.PackV(this.lockTime);
        }
        if (mode & 1) {
            w.WriteVarInt(this.signatureScripts.length);
            for (let i = 0; i < this.signatureScripts.length; i++) {
                if (!this.signatureScripts[i]) {
                    w.WriteVarInt(0);
                }
                else {
                    w.WriteVarInt(this.signatureScripts[i].length / 2);
                    w.PackHs(this.signatureScripts[i]);
                }
            }
        }
        else {
            w.WriteVarInt(0);
        }
        return w.Bytes();
    }
    hashval() {
        const h = (0, sha2_js_1.sha256)((0, sha2_js_1.sha256)(this.encode(0)));
        return hashReverse(h);
    }
    rawDecode(raw) {
        raw = raw.toLowerCase();
        const r = new Reader();
        r.StrToByte(raw);
        this.decode(r);
    }
    decodeBytes(bytes) {
        const r = new Reader();
        r.SetBytes(bytes);
        this.decode(r);
    }
    decode(r) {
        this.version = r.readInt32();
        if ((this.version & 0x20) === 0) {
            const dcount = r.readVarInt();
            this.txDef = [];
            for (let i = 0; i < dcount; i++) {
                let t = r.read(1);
                console.log('t', t);
                t = t[0];
                let c;
                switch (t) {
                    case 0:
                        c = new VertexDef();
                        break;
                    case 1:
                        c = new BorderDef();
                        break;
                    case 2:
                        c = new PolygonDef();
                        break;
                    case 4:
                        c = new RightDef();
                        break;
                    case 5:
                        c = new RightSetDef();
                        break;
                    case 0xfc:
                        c = new SeparatorDef();
                        break;
                }
                c.read(r);
                this.txDef.push(c);
            }
            let count = r.readVarInt();
            this.tIn = [];
            for (let i = 0; i < count; i++) {
                const t = new TinDef();
                t.read(r);
                this.tIn.push(t);
            }
            count = r.readVarInt();
            this.tOut = [];
            for (let i = 0; i < count; i++) {
                const t = new ToutDef();
                t.read(r);
                this.tOut.push(t);
            }
            if ((this.version & 0x10) === 0) {
                this.lockTime = r.readInt32();
            }
            count = r.readVarInt();
            this.signatureScripts = [];
            for (let i = 0; i < count; i++) {
                this.signatureScripts.push(r.readScript());
            }
        }
    }
    modifiable() {
        let m = this.signatureScripts.length === 0;
        for (let i = 0; i < this.tIn.length && m; i++) {
            if (this.tIn[i].previousOutPoint.hash === '0000000000000000000000000000000000000000000000000000000000000000') {
                continue;
            }
            else if (this.tIn[i].signatureIndex !== -1) {
                m = false;
            }
        }
        for (let i = 0; i < this.tOut.length && m; i++) {
            if (this.tOut[i].isSeparator()) {
                m = false;
            }
        }
        return m;
    }
    lockInput(v) {
    }
    inputOf(tokenType) {
    }
    outputOf(tokenType) {
        let sum = BigInt(0);
        for (let i = 0; i < this.tOut.length; i++) {
            if (this.tOut[i].isSeparator() || this.tOut[i].tokenType !== tokenType) {
                continue;
            }
            sum += this.tOut[i].value;
        }
        return sum;
    }
}


`;
