import { sha256 as nobleSha256 } from "@noble/hashes/sha2.js";
import bigInt from "big-integer";

/**
 * Creates a shimmed 'require' function for the contract runner environment.
 * This allows the generated code (which uses CommonJS require) to access
 * necessary libraries that are available in the bundled application.
 */
export function createRequireShim() {
  return (moduleName: string) => {
    switch (moduleName) {
      case "@noble/hashes/sha2":
      case "@noble/hashes/sha2.js":
        return { sha256: nobleSha256 };
      case "big-integer":
        return bigInt;
      default:
        throw new Error(
          `Module '${moduleName}' is not available in the contract runner environment.`
        );
    }
  };
}

import { BUNDLED_UTILS_CODE } from "./bundledUtils";

/**
 * Executes the generated contract script in a sandboxed-like environment.
 *
 * @param scriptCode The full JavaScript code string (generated by generate_template.ts)
 * @returns An object containing all contract methods
 */
export async function runContractScript(scriptCode: string): Promise<any> {
  // Prepend bundled utils (MsgT, Base58, etc.) to the user script
  const fullScript = BUNDLED_UTILS_CODE + "\n" + scriptCode;

  console.log("fullScript", fullScript);

  const requireShim = createRequireShim();

  try {
    const runnable = new Function("require", fullScript);
    const methods = runnable(requireShim);
    return methods;
  } catch (error) {
    console.error("Contract Runner Execution Failed:", error);
    throw error;
  }
}

/**
 * Run a specific method from the contract script.
 *
 * @param scriptCode The full JavaScript code string
 * @param methodName The name of the method to execute
 * @param params Optional parameters to pass to the method
 * @returns The result of the method execution
 */
export async function runContractMethod(
  scriptCode: string,
  methodName: string,
  ...params: any[]
): Promise<any> {
  const methods = await runContractScript(scriptCode);

  if (!methods[methodName]) {
    throw new Error(
      `Method '${methodName}' not found in contract. Available methods: ${Object.keys(
        methods
      ).join(", ")}`
    );
  }

  if (typeof methods[methodName] !== "function") {
    throw new Error(`'${methodName}' is not a function`);
  }

  return await methods[methodName](...params);
}

/**
 * Get available method names from the contract script.
 *
 * @param scriptCode The full JavaScript code string
 * @returns Array of method names
 */
export async function getContractMethods(
  scriptCode: string
): Promise<string[]> {
  const methods = await runContractScript(scriptCode);
  return Object.keys(methods).filter(
    (key) => typeof methods[key] === "function"
  );
}
